FROM jenkins/jenkins:lts

USER root

# Copy official static Docker CLI binary directly into system PATH
COPY --from=docker:cli /usr/local/bin/docker /usr/local/bin/docker

RUN curl -fL https://install-cli.jfrog.io | sh && chmod +x /usr/local/bin/jf

# Create dedicated docker group and add jenkins user
RUN groupadd -g 999 docker && usermod -aG docker jenkins

USER jenkins
